### PR TITLE
Added default http port driver as a constant

### PR DESCRIPTION
**Pull request by xavismeh**
Would it be possible to have a new 4.6.4 tag once the PR gets validated plz? 🐼

### CODE REVIEW

**Comment by Nyholm** [comment]
You want it to be a constant because it should be coherent with the Bolt driver, right? https://github.com/graphaware/neo4j-bolt-php/blob/master/src/Driver.php#L27

**Comment by xavismeh** [comment]
That's it

**Comment by ikwattro** [comment]
4.6.4 released

**Comment by Nyholm** [comment]
You are great! Thanks!

**Pull request merged**
