### PR TITLE
Make sure it is clear what client we using

### PR DESCRIPTION
**Pull request by Nyholm**
Related to #88

### CODE REVIEW

**Comment by ikwattro** [comment]
Thanks @Nyholm , would you be able to add a small test that just instantiate a client with the timeout setting ?

**Comment by Nyholm** [comment]
That test should go to https://github.com/php-http/curl-client/ in the case of Curl client.
And to https://github.com/guzzle/guzzle if one is using the Guzzle client. That is far out side the concern of this library. (Which is a good thing) =)

**Comment by ikwattro** [comment]
Yes, you're right. Thanks for the PR.

**Comment by 0xfff** [comment]
'''
$options = [
        CURLOPT_CONNECTTIMEOUT => 99, // The number of seconds to wait while trying to connect.
        CURLOPT_SSL_VERIFYPEER => false   // Stop cURL from verifying the peer's certificate
    ];
    $httpClient = new Client(null, null, $options);
    $config = \GraphAware\Neo4j\Client\HttpDriver\Configuration::create($httpClient);

    $neo4j  = ClientBuilder::create()
            -> addConnection('default', http://neo4j:psswd@localhost:7474, $config)
            -> build();
'''
btw i'm assuming that in the addConnection line we are passing the variable `$config` in the readme it is `config`

So that code passes but when i try to execute a query i get an exception of "Unsupported Media Type"
should i be setting the Media Type somewhere?

**Comment by Nyholm** [comment]
> btw i'm assuming that in the addConnection line we are passing the variable $config in the readme it is config

Im not sure what you mean. There are two variables, `$options` (for HTTP client) and `$config` (for Neo4j)

> So that code passes but when i try to execute a query i get an exception of "Unsupported Media Type"

Im not sure about why you get that exception.

**Comment by 0xfff** [comment]
`$config` vs `config` in the readme. Readme is missing the `$` in front of `config`

Can you confirm that you can connect to a neo4j instance execute a query, and get results back with the connection as specified above?

**Comment by 0xfff** [comment]
the exception is coming from the use of Httplug, if i use the following to build a connection I can execute a query and get results back (of course longer running queries timeout after 5s.):
```
use GraphAware\Neo4j\Client\ClientBuilder;
    $neo4j  = ClientBuilder::create()
            -> addConnection('default', http://neo4j:psswd@localhost:7474)
            -> build();
```
using the code specified in the [comment](https://github.com/graphaware/neo4j-php-client/pull/112#issuecomment-311730727) earlier does throw the mentioned exception

**Comment by Nyholm** [comment]
Okey @0xfff, I found the issue. 
The code in the example is correct. But the CurlClient is way more strict than Guzzle (the one you get if you do not specify anything) AND the source had a minor bug (see #114). 

After #114 is merged you will be able to use the code in the example.


-----

You could configure the Guzzle client as well. You would do something like:

```php
$httpClient = \Http\Adapter\Guzzle6\Client::createWithConfig(['timeout'=>10]);
```

**Comment by Nyholm** [comment]
Could this doc PR get merged?

**Comment by ikwattro** [comment]
Sorry, merged now

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
