### PR TITLE
global cs fixes (including configuration of php_cs)

### PR DESCRIPTION
**Pull request by kbsali**
while we are at it... ;)

### CODE REVIEW

**Comment by kbsali** [comment]
:+1: thanks! ;)

**Comment by ikwattro** [comment]
@kbsali I didn't merged this PR. The whole test suite was breaking with the CS due to renaming of namespaces. Check here : https://travis-ci.org/graphaware/neo4j-php-client/jobs/171109355

**Comment by ikwattro** [comment]
https://github.com/graphaware/neo4j-php-client/pull/66/files#diff-99e6e05b31bf72529f8c45189db7d883R12

**Comment by kbsali** [comment]
@ikwattro true, it was failing! 
But rather than closing my PR 5 months after opening it, you could have point out this problem, i would have fixed it, etc...
Nevermind, my comment from yesterday remains.

**Comment by ikwattro** [comment]
You're right, sorry about that. I closed to just say you can re-open when fixed.

**Pull request closed without merging**
